services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["--config", "/app/config/docker.config.yml"]
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./config:/app/config:ro
    environment:
      - DATABASE_FILE=/app/data/lean-view.sqlite
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - LOG_LEVEL=info
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 3s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx
      args:
        - VITE_API_URL=/api
    ports:
      - "3000:80"
    depends_on:
      - backend
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  default:
    name: leanview-network
